spring:
  zipkin:
    base-url: zipkin:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: commissions-service
          uri: lb://commissions-service
          predicates:
            - Path=/api/v*/commissions*,/api/v*/commissions/*,/api/v*/employees/*/commissions*,/api/v*/receipts*,/api/v*/receipts/*,/api/v*/commissions/*/receipts,/api/v*/commissions/*/approveByManager
          filters:
            - AuthFilter
        - id: employees-service
          uri: lb://employees-service
          predicates:
            - Path=/api/v*/employees*,/api/v*/employees/*,/api/v*/managers*,/api/v*/managers/*,/api/v*/managers/*/employees*
          filters:
            - AuthFilter
        - id: cms-auth-server
          uri: lb://cms-auth-server
          predicates:
            - Path=/api/v1/auth/*,
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka