version: '3.9'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - commissions-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27888:27017"
    volumes:
      - /data/db:/data/db
    networks:
      - commissions-network

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - commissions-network

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    networks:
      - commissions-network
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - commissions-network

  discovery-service:
    image: manuelrojas19/cms-discovery-server
    ports:
      - "8761:8761"
    networks:
      - commissions-network

  config-server:
    image: manuelrojas19/cms-config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    networks:
      - commissions-network
    environment:
      eureka.client.serviceURL.defaultZone: http://discovery-service:8761/eureka
      eureka.instance.prefer-ip-address: "true"

  auth-server:
    image: manuelrojas19/cms-auth-server
    ports:
      - "8000:8000"
    depends_on:
      - discovery-service
      - kafka
      - config-server
      #      - postgres
      - zipkin
    networks:
      - commissions-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
      eureka.client.serviceURL.defaultZone: http://discovery-service:8761/eureka
      eureka.instance.prefer-ip-address: "true"
      spring.zipkin.base-url: http://zipkin:9411
      spring.datasource.url: jdbc:postgresql://postgres:5432/cms_auth_db
    #      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/cms_auth_db
    restart: on-failure

  employees_service:
    image: manuelrojas19/cms-employee-service
    ports:
      - "8101:8101"
    depends_on:
      - discovery-service
      - config-server
      - kafka
      #      - postgres
      - zipkin
    networks:
      - commissions-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
      eureka.client.serviceURL.defaultZone: http://discovery-service:8761/eureka
      eureka.instance.prefer-ip-address: "true"
      spring.profiles.active: local,local-discovery
      spring.zipkin.base-url: http://zipkin:9411
      spring.datasource.url: jdbc:postgresql://postgres:5432/employees_service_db
      #      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/employees_service_db
      spring.config.import: "optional:configserver:http://config-server:8888"
    restart: on-failure

  commissions-service:
    image: manuelrojas19/cms-commission-service
    ports:
      - "8201:8201"
    depends_on:
      - discovery-service
      - config-server
      - kafka
      #      - mongo
      - zipkin
    networks:
      - commissions-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
      eureka.client.serviceURL.defaultZone: http://discovery-service:8761/eureka
      eureka.instance.prefer-ip-address: "true"
      spring.data.mongodb.host: mongo
      #      spring.data.mongodb.host: host.docker.internal
      spring.profiles.active: local,local-discovery
      spring.zipkin.base-url: http://zipkin:9411
      spring.config.import: "optional:configserver:http://config-server:8888"
    restart: on-failure

  gateway:
    image: manuelrojas19/cms-api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - discovery-service
      - config-server
      - employees_service
      - commissions-service
      - auth-server
    networks:
      - commissions-network
    environment:
      eureka.client.serviceURL.defaultZone: http://discovery-service:8761/eureka
      eureka.instance.prefer-ip-address: "true"
      spring.zipkin.base-url: http://zipkin:9411
    restart: on-failure

networks:
  commissions-network:
